### ISSUE TITLE
Don't allow readers to ignore staff members

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#1023]
AC:
- If a user ignores a staff member, it gives a warning notification "Staff members cannot be ignored"
- The staff member is not ignored and not added to the user's ignore list

**Comment by dagjaneiro** [comment]
Hi! I'd like to tackle this issue. 

Since I'm new to the project can you clarify if by warning notification you mean the same notification system used to display errors?

Something like this:

![image](https://user-images.githubusercontent.com/10207818/31309503-0220f34e-ab7f-11e7-8e2c-abcd8b57db20.png)

**Comment by kgardnr** [comment]
Fixed in #1078
