### ISSUE TITLE
Keyboard shortcuts to move between Mod Queues

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#1042]
AC:
- Add keyboard shortcuts `1` `2` `3` `4` `5` etc to move between queues in order of queues.
- Would have to be careful with how to handle plugin-generated queues potentially?

**Comment by yonidor** [comment]
Hi, i'm willing to give that a look :)

**Comment by kgardnr** [comment]
Great @yonidor! Thank you and welcome :)

**Comment by yonidor** [comment]
@kgardnr 10x!
This is my first try of open source contribution, so i might need some guidance :)

I'm trying to setup and run the Talk project, and i have an issue with loading the assets  (_bundle.js_ is loaded from a wrong path... it is generated in the _dist_ folder, but the views try to load it from the _client_ folder ).
Is it OK to discuss it here, or you prefer a more direct way?

**Comment by kgardnr** [comment]
Welcome @yonidor! No problem at all!

Have you followed all the setup instructions here: https://coralproject.github.io/talk/

Are you getting any errors when you run `yarn`, `yarn build` or when you start the server with `yarn start`?

**Comment by yonidor** [comment]
@kgardnr 
`yarn` and `yarn build` pass successfully
The instructions ("Installation from source") says to run `yarn dev-start`. when i ran that, no errors were raised, i was able to load the site, but i've encountered the assets loading issue.
When running `yarn start`, i get an error
```
/Users/ydor/dev/talk/config.js:192
  throw new Error('TALK_ROOT_URL must be provided');
  ^

Error: TALK_ROOT_URL must be provided
    at Object.<anonymous> (/Users/ydor/dev/talk/config.js:192:9)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
```

guess it doesn't load `.env` when not in dev mode?

**Comment by wyattjoh** [comment]
The `client` folder is mapped to the `dist` folder through express routing, so that's not the issue.

When developing, ensure you use `yarn dev-start` which will load the `.env` file.

When in production, it's expected that you've loaded the configuration into the environment through an external provider (such as a service file, or docker) and leave that configuration up to that.

`TALK_ROOT_URL` must always be provided, as it's the base for all requests made back to the api server.

**Comment by yonidor** [comment]
@wyattjoh thanks. i don't know what happened, but suddenly `yarn dev-start` started working. Now i have a different problem. When i try to finish the registration (The "Finish install" button) i get this message in the console:
![image](https://user-images.githubusercontent.com/6272947/31255639-7f484b96-aa36-11e7-8db3-8de76e841dfc.png)

Any idea?

**Comment by wyattjoh** [comment]
What is your value for `TALK_ROOT_URL`?

**Comment by yonidor** [comment]
`TALK_ROOT_URL=http://127.0.0.1:3000`
from my `.env` file

**Comment by wyattjoh** [comment]
I would suggest stopping the `yarn dev-start` and starting it again. The `dev-start` will not reload the `.env` every time, only once when you first load it.

**Comment by kgardnr** [comment]
Any luck @yonidor?

**Comment by MuraraAllan** [comment]
@yonidor I Got the same error with 

> yarn run start

 , we are not under a production Environment. Use dev-start, it will work.

What i suggest you in order to fix this problem you are facing in your Development environment is : 
try out this sequence : 
If you have MongoDbCompass, RoboMongo or any mongo client, wipe out your Mongo Database.  (Picture 1)

From main folder of talk, run this comand :
`./bin/cli -c .env setup` (Picture 2)
Fill with the values of Picture 2.
Then you have all up and running, you can choose either local Asset or Remote Asset - demo on site (that is why i'm passing an array as Whitelisted Domain value).

![screenshot from 2017-10-06 13-05-21](https://user-images.githubusercontent.com/8569238/31287296-27d493e0-aa97-11e7-86e1-299065af10a1.png)
**Picture 1**

![screenshot from 2017-10-06 13-02-48](https://user-images.githubusercontent.com/8569238/31287211-e3fb6a18-aa96-11e7-8205-10b8c28020a3.png)
**Picture 2**


Actually Picture 1 has the values too :(

**Comment by yonidor** [comment]
@kgardnr no luck :(
@MuraraAllan Followed your instructions, and now i get the following screen on the homepage (http://127.0.0.1:3000)
![image](https://user-images.githubusercontent.com/6272947/31305957-3d8a56d6-ab4e-11e7-82d0-e8edd8e925bd.png)

The preloader keeps on spinning, and the console shows this error
![image](https://user-images.githubusercontent.com/6272947/31305983-d70cf3f4-ab4e-11e7-989b-1ce399a3b0c4.png)

When i go to 'Admin', i get to a login page, but when entering my credentials, nothing happens, and i can see this call pending in the console..
![image](https://user-images.githubusercontent.com/6272947/31306005-51656064-ab4f-11e7-839b-e16685d07a4c.png)

**Comment by MuraraAllan** [comment]
Great to read that @yonidor... It's my mistake!

Instead of passing an array of values to your whitelist, you should pass 127.0.0.1. 
I probably don't restart my environment when i sent you the picture and assumed that a array on the whitelist field will be converted in 3 values. :)
You don't need to make all the steps again, just open a mongoDB client and edit the whitelist.

db.settings.domains.whitelist , reach this document and edit to 127.0.0.1, or just add a new record in the db.settings.domains.whitelist :>

![screenshot from 2017-10-07 11-37-56](https://user-images.githubusercontent.com/8569238/31308869-fbd2a5bc-ab53-11e7-8be5-f5268a110dd7.png)

**Comment by yonidor** [comment]
@MuraraAllan nope, still getting the "Not logged in" error in the console. Thanks anyway :)

**Comment by MuraraAllan** [comment]
There is something very weird going on @yonidor  and i would love to catch up what it is.

Look, even if localhost is a loopback to 127.0.0.1, localhost / local will not render the things in right way using Talk as long as i debug here. 

localhost:3000 will not work, 127.0.0.1:3000 will work.
For some reason the address of the asset_url that your browser is assuming is "localhost", i bet you get an "invalid asset_url" in your node console.

What OS are you using? 

Did you tryout with localhost:3000 and 127.0.0.1:3000 ?

What happens when you reach, directly, 127.0.0.1:3000/admin/moderate ?

I reproduced the bug you are getting and have the exactly same problems ( and they are not exact related to the log in message in your browser, but to the asset_url that logs out in your node console ) on localhost:3000 , bug free on 127.0.0.1:3000.


Another suggestion :


Give a try to delete everything from your directory and fork again, if you don't made any changes yet.

If you made any changes you can use this to try to merge without overwriting your changes :
`git remote add upstream https://github.com/coralproject/talk`
`git fetch upstream`
`git merge upstream/master`

then build out your app again, delete your mongo database and install it again.


Last guess, hope it works :}

**Comment by wyattjoh** [comment]
The asset url matching component isn't that smart to try and resolve ip addresses, hence why if you set the whitelist to include `127.0.0.1`, `localhost` won't work. The error in the console for `Not logged in` is fine, and is returned if the browser see's that you're not logged in.

Double check your privacy settings on your browser to ensure you aren't blocking cookies/js, as that might impact some of the features.

**Comment by yonidor** [comment]
@MuraraAllan @wyattjoh Sorry, very busy week, will try to give it another go this evening

BTW, no way i'm blocking cookies/JS, if that was the case your project would probably not be the first time i encounter issues :)
