### ISSUE TITLE
Inability to treat directory same thread as directory/index.html

### ISSUE THREAD

**Issue by MrBryan** [coralproject/talk#1148]
### Expected behavior

Expect as with disqus that the platform will detect that directory index pages e.g website.com/folder/index.html  is the same content as website.com/folder/

### Actual behavior

Talk treats these two URLs as separate threads

### Steps to reproduce behavior

Load page in the two ways described above

**Comment by MrBryan** [comment]
Perhaps `<link rel="canonical" > ` tags can be the authority to be consistent with social media etc

**Comment by wyattjoh** [comment]
When running in production @MrBryan, Talk will prefer the `<link rel="canonical" >` tag instead of inferring it from the current url in the url bar:

https://github.com/coralproject/talk/blob/ff9ae035224865ee2ed5ae30100a5632fd9d41e2/client/coral-embed/src/index.js#L75-L91

If this doesn't work for you, you can also explicitly manage the assets loaded into Talk with some of the guides here:

https://github.com/coralproject/talk/blob/ef49d9a3d2acc4d2fc03b00e0c872dfbc57f005a/docs/_docs/04-02-plugins-quickstart.md

And a description of the process here:

https://github.com/coralproject/talk/blob/ef49d9a3d2acc4d2fc03b00e0c872dfbc57f005a/docs/_docs/00-01-faq.md#how-are-new-storiesassets-added-to-talk-is-there-an-api

**Comment by MrBryan** [comment]
Aha ok I am in dev mode thanks
