### ISSUE TITLE
Comment Flagging status Flag/Flagged/?Moderated?

### ISSUE THREAD

**Issue by DHorse2** [coralproject/talk#1254]
### Expected behavior
Once a moderator has actioned a flag it should show a change in status.
For example, having flagged my own post I would like to know it was seen by a moderator.
### Actual behavior
I suspect it (my flag action) remains permanently flagged so that I don't do it again by mistake.
### Steps to reproduce behavior
This would have to be tested by moderation staff.
Could I get a link to where the flag is documented?

**Comment by kgardnr** [comment]
Hey @DHorse2! So the behavior here is that once a comment is Reported, it shows as reported, you can see that here:

<img width="529" alt="reported" src="https://user-images.githubusercontent.com/1077300/34680998-86b6cffc-f468-11e7-94f4-30a57e448332.png">

A comment that is reported shows in the Reported queue for moderation.

<img width="1273" alt="reported_queue" src="https://user-images.githubusercontent.com/1077300/34681015-930d46a0-f468-11e7-94a7-f8ab140910dc.png">

Depending on the newsroom and the customizations they've made to the software, there can be lots of other queues and report types, etc, but this is basic functionality out of the box for Talk.

We don't have any plans to alert users of moderation actions that moderators have taken; one reason for that is because commenters could easily game the system. But I will bring this up in our next product meeting and can let you know if/when it comes up on our roadmap.

Thank you!

**Comment by kgardnr** [comment]
Confirmed this is also working as expected on TI:

<img width="709" alt="reported_ti" src="https://user-images.githubusercontent.com/1077300/34681654-8d0493ba-f46a-11e7-9df2-c6cca5f37cda.png">

**Comment by DHorse2** [comment]
This is going to sound bizarre, but do my View Options include an alphabetical list?
