### ISSUE TITLE
Users with username.status of "UNSET" cannot comment (4.0.0)

### ISSUE THREAD

**Issue by Jetbo** [coralproject/talk#1295]
### Expected behavior

Users that login with a non-local provider (like Facebook) get a value of "UNSET" under `user.status.username.status`.  User can run `CreateComment` mutation when logged in.
https://github.com/coralproject/talk/blob/93bda87ad061a2dc5eb8dc5b65a579a20efb76f7/services/users.js#L390-L402  Note this worked fine in 3.9.X

### Actual behavior

Users with "UNSET" cannot comment due to this code change for 4.0:
https://github.com/coralproject/talk/pull/1154/files#diff-aaf40ad3b2e134d7ca8ecab768181cf5R19
which fails this check:
https://github.com/coralproject/talk/blob/08b1cada7e4a7fff98e99fe9d2209fbdfc69c526/graph/mutators/comment.js#L560

### Steps to reproduce behavior

Add test case
```
{ user: new UserModel({
        status: {
          username: {
            status: 'UNSET'
          }
        }
      }), error: null },
```
to `users with different statuses`
https://github.com/coralproject/talk/blob/08b1cada7e4a7fff98e99fe9d2209fbdfc69c526/test/server/graph/mutations/createComment.js#L74

**Comment by wyattjoh** [comment]
This behavior is intentional. Users who signup using the Facebook provide must confirm or set their username before they are permitted to comment.

**Comment by kgardnr** [comment]
Hi @Jetbo, thanks for posting this! 

To clarify, a user with an UNSET username is one who has signed up with Facebook but not yet set a username. Usernames are required in order to comment, and are the second part of the Facebook registration flow.

4.0.0 is a major refactor of how user statuses and abilities function, and this is a change that was made to better this part of Talk.

Let me know if that answers your question!
