### ISSUE TITLE
External Usernames: Only Accepts Letters

### ISSUE THREAD

**Issue by Jetbo** [coralproject/talk#1337]
Hello, I was wondering why external logins only accept usernames with letters in them.  Anything else in the username gets trashed:

https://github.com/coralproject/talk/blob/86f4ae4b6da2eae020fa1d6b2a593eb0739df1bd/services/users.js#L387

https://github.com/coralproject/talk/blob/86f4ae4b6da2eae020fa1d6b2a593eb0739df1bd/services/users.js#L361-L363

Why does this just happen silently instead of returning a malformed error?  Also are there plans to document requirements like this?

We looked through the commit history and it seems like it almost wasn't intentional.  It's an interesting dependency because any system we write that uses usernames as input doesn't have visibility to this special behavior.  I had to track it down to figure out what was going on.

Thanks!

**Comment by wyattjoh** [comment]
The function `findOrCreateExternalUser` was originally created for us to use with providers like Facebook + Google, and was not intended to integrate with external authentication systems. Facebook allows you to create a username, and this was to "cast" that username down.

If you are writing a plugin to handle your own auth system, or an importer to move external data into Talk you should instead just create the User yourself and save it directly rather than using the service method to do so.

**Comment by Jetbo** [comment]
Is this moving to the Facebook plugin then?  Otherwise it's awfully confusing.

**Comment by wyattjoh** [comment]
Fair point! We can move that code off to our `talk-plugin-facebook-auth`.

**Comment by wyattjoh** [comment]
As a recommendation as well, typically when external newsrooms integrate auth with their own internal usernames they store them in the metadata field, as the username field we use includes indexes on uniqueness which isn't always the same for all orgs.

**Comment by Jetbo** [comment]
Roger, thanks for the info!
