### ISSUE TITLE
Permission error when deploying on AWS

### ISSUE THREAD

**Issue by KaivG** [coralproject/talk#1347]
### Expected behavior
I tried deploying talk on AWS via docker and Beanstalk as well as from source, after running it successfully locally.

### Actual behavior
No matter what approach, I kept getting timeouts and failures, when trying to debug it seems to come down to a permission error:

$ ./bin/cli plugins reconcile --skip-remote
': No such file or directory

### Steps to reproduce behavior

- Clone Repository
- Install aws eb-cli
- run eb init, set up newest docker ce environment
- run eb create

Any idea how to get it running?

**Comment by wyattjoh** [comment]
What version are you trying to deploy to EB?

**Comment by KaivG** [comment]
I tried with version v4.0.0. I noticed that it may be related to out of memory error that happens while webpack runs possibly because of a memory leak with postcss-loader v1.3.x that talk uses: https://github.com/webpack/webpack/issues/1914 It was apparently fixed in v2.x

I also noticed that AWS Elastic beanstalk by default spins up a t2.micro instance with 1GB of ram, which together with the memory leak may cause the yarn build to fail. I will try to do some more testing in the next days.

**Comment by wyattjoh** [comment]
Unfortunately, we can't control how much memory some of the build processes takes until it's patched upstream.

A possible solution is to avoid the issue entirely, by running a Docker container instead of the raw application itself. This seems like a guide to doing just that with EB:

https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_docker.html

**Comment by kgardnr** [comment]
Hey @KaivG, have you been able to get Talk up and running?
