### ISSUE TITLE
TRUST_THRESHOLD Configuration

### ISSUE THREAD

**Issue by aguilarm** [coralproject/talk#1404]
### Expected behavior
I think the Trust concept is cool, but I would expect it to be either disabled by default or available for configuration in the Talk Admin interface.  It does not seem to be something that a sysadmin should be concerned with.  If enabled by default, settings and behavior of feature should be discoverable by moderators.  This could be either in **Configure**>**Moderation Settings** and/or with some text describing the state of a user's trust on the admin user detail popout.

### Actual behavior
`TRUST_THRESHOLD`, and the functionality it adds, is hidden away in an environment variable in the Advanced Configuration.  From what I can tell there is no way for a moderator to find out how Trust works from the admin interface.

So 'As a moderator, I can see and/or change the trust threshold both globally and as it pertains to an individual user so that I can understand the side effects/implications of my actions when rejecting comments.'

**Comment by kgardnr** [comment]
Hey @aguilarm - yep, we do want to get to this in the future for sure - it's just about finding the time to prioritize it.

If this is something you need, we would *love* if you decided to contribute it. If you wanted to propose a solution, our team and chime in with any feedback, and then you can be off to the races :)

**Comment by aguilarm** [comment]
@kgardnr 

Cool, I think we're mostly going to be banning users instead of moderating individual comments so this is not immediately pressing.  Noticed the behavior when we were poking around and didn't see an issue on the repo yet.

I may come back to this if it becomes an issue for moderators when we start using Talk in the wild.

I would suggest disabling this feature by default until it is more fleshed out but now that I know about it I can work with it for now.

**Comment by kgardnr** [comment]
Make sure you read the Docs and especially the Product Guide, when you're getting acquainted with the full suite of Talk features - https://coralproject.github.io/talk/how-talk-works/

A lot of the parts we have built into core (vs making it easily swappable, like in our non-default plugins and recipes - https://coralproject.github.io/talk/additional-plugins/), is because we have done copious amounts of research - as well as working with over 150 newsrooms, including some of the top ones we now have using Talk actively. You can read more about our research here: https://coralproject.net/research.html

For things like Trust, this is part of what makes us different from other commenting platforms. We know this is a valuable feature for newsrooms, and we've found managing the threshholds via environment variable (because this doesn't change often, nor do you necessarily want it to) definitely fits the moderator need here.

**Comment by kgardnr** [comment]
You can also follow our product backlog on Pivotal - https://www.pivotaltracker.com/n/projects/1863625

This is where we plan our sprintly product work and manage our roadmap.

**Comment by aguilarm** [comment]
@kgardnr 

Ahh, [found the task in pivotal](https://www.pivotaltracker.com/story/show/147300991) and the [trust docs](https://coralproject.github.io/talk/trust/).

With all that considered, popping this configuration into the admin ui and [this task to show karma in the moderation ui](https://www.pivotaltracker.com/story/show/154483779) would take care of all of my concerns.

If it works better for you, you can close this issue in favor of managing them in pivotal.

Thanks for the direction!

**Comment by kgardnr** [comment]
Cool, thanks for the feedback! Keep us posted as you roll out Talk, we love to see how people are using it! <3
