### ISSUE TITLE
"Historical" items

### ISSUE THREAD

**Issue by jde** [coralproject/talk#153]
The purpose of this discussion to accomplish two things:

1. Simple and standard way of knowing the current `status` of an item (aka, asset, comment or user)
1. A standard way of knowing everything that's happened in the lifecycle of an item, who (if anyone) took the action to make it so, and when it happened.

Proposal:
Current Status:
To know current status, each field has a `status` field (string). This allows the status of an item to be queried efficiently and naturally travel with the item.

History:
Tracked as a sequence of `events`, containing:
* what (status change) 
* who (user_id) 
* when (timestamp) 
* In the future we may want to include a _why_ field, such as `notes`

Possible places to store historical events:

1. as an array on the item itself
1. in a single `events` collection (in which case we would add the item_type and item_id to the schema in the same way we do for actions.)
1. in multiple events collection, aka `user_events`, `asset_events`, etc...

Discuss!

**Comment by wyattjoh** [comment]
I added a comment on a related PR: https://github.com/coralproject/talk/pull/161#issuecomment-266492569

- I just don't think that an asset holds the same responsibilities that a comment has, so I don't think that we necessarily need to break out the functionality from the `closedAt` field already provides

- The `status` of a asset is based on a temporal value (the time) and not the "most recent status" so the determination of the current status becomes much more complex on the FE and the BE
- If this were just a text field of status (like in the comment) I'd agree that it would work. But the closed status doesn't make sense that we "need" to store the history especially because of the overhead of managing the data models for it.

I just don't think this is the right approach.

**Comment by jde** [comment]
We are moving away from 'item level' architecture and will be addressing historicity at a type by type basis.  Closing.
