### ISSUE TITLE
Feature Idea: Configurable promise module

### ISSUE THREAD

**Issue by angelo-hub** [coralproject/talk#1578]
#### Intended outcome:
As a developer, it would be great if I could configure the promise library used within the project either by using something like [optional-require](https://www.npmjs.com/package/optional-require) and configurable through the configuration YAML files. It would be great if I could choose to use [bluebird](https://www.npmjs.com/package/bluebird) as the project wide default, as long as choosing the promise library wouldn't have unexpected consequences.

Currently have this set on each individual custom plugin

#### Version and environment
4.3.0 Alpine Docker container

**Comment by wyattjoh** [comment]
Thanks for the feature request @AngefloMusic!

We currently want to keep all of our codebase as close to the living standard as possible rather than swapping out what we get for free with ES6 with a third party library. You can feel free to use bluebird in your plugins or externally, but we won't be supporting this in core within the foreseeable future.
