### ISSUE TITLE
Close/Open Comments

### ISSUE THREAD

**Issue by gabelula** [coralproject/talk#159]
Story: https://www.pivotaltracker.com/n/projects/1863625/stories/134297345

### Expected behavior

- The 'Close Stream' button in the 'Configure Stream' should have a box to write down the close message. (Otherwise we should have the Asset.closedMessage field not in the Asset but in Settings).
- The endpoint for changing the status of an Asset should change to use closedAt, closedMessage instead of status field

### Actual behavior

- Closing and opening comments is not working (backend and frontend not sync)

### Steps to reproduce behavior

- open the comment thread
- reload the page
- check if it is still open

**Comment by wyattjoh** [comment]
I added a comment on a related PR: #161 (comment)

I just don't think that an asset holds the same responsibilities that a comment has, so I don't think that we necessarily need to break out the functionality from the closedAt field already provides

The status of a asset is based on a temporal value (the time) and not the "most recent status" so the determination of the current status becomes much more complex on the FE and the BE

If this were just a text field of status (like in the comment) I'd agree that it would work. But the closed status doesn't make sense that we "need" to store the history especially because of the overhead of managing the data models for it.

I just don't think this is the right approach.

**Comment by gabelula** [comment]
How do you open back the asset with the closedAt approach? Just null back the field?  I'm ok with that for now actually. We just needed to fix the backend to have it working with the frontend. I can modify the PR for that. 

@jde any thoughts about this?

**Comment by wyattjoh** [comment]
`closedAt: null` or `closedAt: false` would do the same thing there I think @gabelula

**Comment by gabelula** [comment]
It get resolved in the PR https://github.com/coralproject/talk/pull/161 ready for review.
