### ISSUE TITLE
Feature idea: user can view all their comments in My Profile

### ISSUE THREAD

**Issue by clintabrown** [coralproject/talk#1652]
#### Do you want to request a **feature** or report a **bug**?

Feature

#### Intended outcome:

Currently, the My Profile tab only displays Accepted comments to users.

It would be beneficial for users to be able to view all comments they've posted along with their current status (in particular when pre-moderation is enabled).

From a configuration perspective, this could take the form of a new environment variable -

`TALK_PROFILE_SHOW_COMMENTS`: `['ACCEPTED', 'PREMOD', 'SYSTEM_WITHHELD',  'REJECTED']` (default: `['ACCEPTED']`)

From a UI perspective, this could take the form of -

- A status label and class name (for optional styling) applied to each comment in the My Profile tab (preferred) or
- An additional layer of tabs (Accepted, Pre-Mod, System Withheld, Rejected) in the My Profile tab, similar to the tabs (All, Rejected, User History) when viewing a user profile in admin. Perhaps Pre-Mod and System Withheld could be combined into a single Pending tab which sounds more user friendly?

We are happy to implement the feature ourselves but would appreciate if you could validate the idea and/or provide any recommendations before we commence.

#### Actual outcome:

Users can view all comments they've posted in the My Profile tab

**Comment by kgardnr** [comment]
Hey Clint, thanks for writing in!

We decided explicitly not to include this, because it could be abused to try and game the system - if people know which comments were rejected or withheld by certain tools.

I think the idea of showing Pre-mod is interesting, I can bring this up with our team.

Note that if you enable the feature Download My Comments, commenters can download all their comments regardless of their status.

**Comment by clintabrown** [comment]
Thanks @kgardnr - will wait to hear back on opinion re: pre-mod inclusion.
