### ISSUE TITLE
Karma threshold

### ISSUE THREAD

**Issue by hjanuschka** [coralproject/talk#1823]
from our moderator:
> We’ve got too many „reported“ postings. Is it possible to deactivate the „karma“-feature? At the moment it is impossible for us to find „real“ reported postings.

if we reject a post, or two - every following comment is auto-reported, and that way its hard to review.

i think this is the config variable: https://docs.coralproject.net/talk/advanced-configuration/#trust-thresholds

but i am a bit too stupid to figure out how it works.

p.s: we are running in full "moderate" mode. and having a typical user with 30-40% reject rate.

**Comment by kgardnr** [comment]
Hey @hjanuschka, you can increase the comment threshold in the variable. So maybe:

`TRUST_THRESHOLDS=comment:2,-10;flag:2,-1`

This means commenters with even 10 rejected comments (versus their approved) would still be able to comment.

It might be worthwhile to let it go for a while while the ecosystem rebalances itself though - the purpose of karma is to decrease manual moderation because commenters who are likely to get a lot of comments rejected will need to get comments approved before they can re-join the conversation.

It would be interesting to see if your community discourse improves over a few weeks or so time.

**Comment by hjanuschka** [comment]
🤚  hey @kgardnr thx for clarification.

talking to the community department, they dont think, atleast in the current point in time, that use will tend into positiv users. we are no running with `comment:2,-9999`  😱 

many thx, going to close this issue now.
