### ISSUE TITLE
[Megathread] Feature Idea: Native App Support for Talk

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#1827]
This is a megathread to discuss native app support for Talk.

**Comment by belrvn** [comment]
Hi, what is there a way to launch Talk on Android in webview? 
In my situation CoralTalk itself is incapsulated inside of <iframe/> on the html page that is shown on the Android in webview. So to log in with coral talk I am redirected to another page in the same webview to choose between the Facebook or Google authorization. Here is a double problem is that on Android Google is trying to prevent users from authorizing in different webview rather than Chrome browser. So the best UX solution is to open both auths in chrome, so that users have their credentials saved in browsers, rather they need to type them every time. Anyway with some workaround we continue autherization process in the same webview and after getting this 

`https://accounts.google.com/o/oauth2/auth?response_type=code&redirect_uri=URI/auth/google/callback&scope=profile&client_id=ID&from_login=1&as=AS&authuser=0
`

and for Facebook something similar:

`https://URI/api/v1/auth/facebook/callback?code=`

When I return back to the first page in webview and try to update an iframe container nothing happens. Any thoughts about this?

**Comment by jossittelija** [comment]
Having similar issues trying to getting Talk working in iOS and Android apps. 

Most straightforward approach would be to follow Google and Facebook auth recommendations and redirect each authorisation to use browser or app, depending on if users e.g. have authorisation capable apps installed, falling back to browser authentication. After authentication, there should be clear way to return to app / webview and refresh the page to show signed in status in Talk. On iOS, typically redirecting back to app has to be done with custom URL that is capable of switching back to app from browser or separate app, and this is possible either using universal links or custom URL scheme. If switching back to app is made using URLs, at least in iOS either app containing the webview or Talk instance should be able to define this URL on a per app basis, as there may be need to use same Talk comments on different apps and user may have installed several of them. Returning to the right app after sign in is important.

After logging in, Talk plugin should fully work in webview components that are available at the platform, and at the moment on iOS, there are two UI classes, WKWebView and UIWebView which most apps using web content use for web page display. Supporting WKWebView should be the first priority as UIWebView is being deprecated by Apple in iOS 12. 

Easiest approach for hybrid (webview) apps would be that existing Talk plugin and authentication components would be 'webview' aware at least for iOS and Android, and work out of the box when Talk plugin is used in a web page loaded in the webview components used by the platform.

All this of course seems to require additional work on the Talk components involved.

**Comment by jossittelija** [comment]
For those iOS and Android native apps that do not use webviews, best approach would be to have Talk native kits, e.g. for IOS using Cocoapods, that support performing sign-in and reading / writing comments using an API, and allow the apps the freedom to present the comments to the user using per-platform UI techniques. In this case, it may be also good to define UX guideline on so that apps may use common style if they so wish.

**Comment by kgardnr** [comment]
@Belka1000867 @jossittelija you can find docs on this here: https://docs.coralproject.net/talk/embedding-in-native-mobile-apps/

https://coralproject.net/wp-content/uploads/2019/01/IGNNativeComments.pdf
