### ISSUE TITLE
Changing Username with GraphQL - Getting Not Authorized Error

### ISSUE THREAD

**Issue by marykenefick** [coralproject/talk#1830]
#### Do you want to request a **feature** or report a **bug**?
Question

#### Intended outcome:
We are trying to use GraphQL to change a username but keep getting a “not authorized” error. I created a token for an Admin user

#### Actual outcome:

We are getting a “not authorized” error:
{“data”:{“changeUsername”:{“errors”:[{“translation_key”:“NOT_AUTHORIZED”}]}}}

#### How to reproduce the issue:
This is the request we're using:
curl --request POST \
 --url http://localhost:3000/api/v1/graph/ql \
 --header ‘Content-Type: application/json’ \
 --header “Authorization: Bearer [token]” \
 --data ‘{ “query”:“mutation ChangeUsername($user_id: ID!, $username: String!){changeUsername(id: $user_id, username:$username) {errors { translation_key }}}“,”variables”:{“user_id”:“e0e325d5-ebee-4dfb-9f89-81f4f12168a4", “username”:“testusername”}}’

#### Version and environment
Talk version: 4.5.1

**Comment by sherrymorales** [comment]
It appears one can only change his/her own username and when current username has a status of REJECTED. Is there a good way of updating usernames and email addresses using a system admin account?

**Comment by wyattjoh** [comment]
The graph edge that you used to change the username of a user was really only meant for the internal username changing system, not for external systems to instrument changes on behalf of an external system. Unfortunately you would have to implement a plugin that includes that functionality specifically, hence the errors that you’re seeing. Take a look at 
https://docs.coralproject.net/talk/integrating/asset-management for an example.

**Comment by ihardyslide** [comment]
Sorry for re-opening this old issue, but I wanted to ask how it should be done in v7, considering that there are no custom plugins possible anymore?
Basically I need to extract the change username functionality to a seperate page where there is no Coral.
My guess would be some kind of middleware service/app (which authenticates as admin to the Coral API), which forwards the change username requests from the frontend to the Coral API.

**Comment by wyattjoh** [comment]
You can use the `updateUserUsername` mutation in the GraphQL API in order to perform that operation.

https://github.com/coralproject/talk/blob/2bda76ae5070b8d55b202ab3f5d246b4fbafa345/src/core/server/graph/schema/schema.graphql#L7270-L7285

https://github.com/coralproject/talk/blob/2bda76ae5070b8d55b202ab3f5d246b4fbafa345/src/core/server/graph/schema/schema.graphql#L8954-L8956

**Comment by ihardyslide** [comment]
@wyattjoh Thanks for your answer, but according to the docs, I would need an access token in order to call the mutation.
But the docs also clearly state that: 
"Only administrative users can integrate with the API directly. This means that the Coral API cannot be used for a native app integration which would require non-administrative users to interact with the API."

As far as I understand, this is exactly what I would do, if I would create a token which will be used on a seperate page by normal users. Is this correct?

Maybe to re-explain the idea and clear things up a bit:
Normal commenters should be able to change their username on a custom page, where there is no Coral integration. (e.g. Some dedicated Userprofile-Settings page)

**Comment by wyattjoh** [comment]
If you create the administrative access token, and have it stored on a server, then what you can do is call directly from the server to the Coral instance. The documentation you quoted references calling Coral _directly_ from a native app, where in that case the access token would need to be available within that app's source code (on iOS/Android/macOS/Windows). The access tokens used by Coral are _designed_ for server-to-server calls. In this case, you'd have the following:

1. User navigates to `https://my-website-not-coral.com/account/change-username`
2. User types in new username to use, hits submit
3. Server validates username
4. Server sends username along with the users ID to Coral using the administrative access token to the `updateUserUsername` mutation
5. Coral changes the username of the aforementioned user

In this scenario, the "User" never had access to the access token, and the user was able to interact with your site to change their username without Coral included on it.

**Comment by ihardyslide** [comment]
@wyattjoh Thanks.
It's much clearer to me now.
So an extra service is the way to go.
