### ISSUE TITLE
System Admin should not be able to be banned

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#1918]
#### Do you want to request a **feature** or report a **bug**?
**Bug**

#### Intended outcome:
This is a weird edge case we've come across sometimes, I believe it's only able to achieve this by manipulating the database directly; to stop this from happening, we should just prevent the system admin from being banned or suspended in any way.

**Comment by cdtinney** [comment]
The description says "**prevent** the system admin from being banned/suspended" but the title says "system admin **should** be able to be banned".

Which one is it? How could we prevent database manipulation in either case?

**Comment by wyattjoh** [comment]
That was a typo @cdtinney! Thanks for catching it!

**Comment by cdtinney** [comment]
@wyattjoh I assume an expected solution prevents DB manipulation from affecting behaviour.

How about something like:
- Ensure `User.suspension` and `User.banned` are set to defaults on startup for System Admin user
- Re-generate System Admin user row if deleted (on startup)

**Comment by mazzi** [comment]
Hi @kgardnr @wyattjoh !
Some questions about this bug/gap:
* How many Administrators can exist per talk installation? Assuming more than one, the expected behavior then is that administrators cannot ban _any_ administrator or only himself?
* An administrator cannot do any action on the user detail drawer  (`/admin/moderate/`) to himself but to the rest of the users with comments. That's correct?
* On the section `/admin/community/people` an administrator can execute any action on any user (even himself). That's also correct?

Based on the answers, I'll _probably_ think on a solution. 😅 

Thanks a lot!

**Comment by kgardnr** [comment]
This is addressed in v5
