### ISSUE TITLE
Username change box should show validation errors if username is not valid

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#1924]
#### How to reproduce the issue:
1. Try and change your username to something invalid, e.g. "username@#!" (special characters are not allowed)
2. Your save will not take effect, but there is no feedback to the user as to why

**Comment by moogacs** [comment]
I wanna take this if still up , but just need direct access ?

**Comment by kgardnr** [comment]
Hey @moogacs what do you mean by direct access?

But yes, it's all yours!

**Comment by saskakol** [comment]
Hi @kgardnr! Could I pick this one up, since it looks like it hasn't been active in a while?
I created a local instance of talk, but I'm wondering if I can remove the time limit on changing a username, since it's stopping me from trying to test this at all. Is that possible? I tried to look through some of the docs and configs, but didn't find anything. 
And for additional clarification: This is about the "change username" box in the embedded comment box, right?

Thanks 😄

**Comment by saskakol** [comment]
Never mind about the time limit; I found the correct place to change it 👍 
As far as I can see, the validation is already stopping the user from clicking the Save button, but there is no other error message.  Going to take a look at how to add that now. 🙂
