### ISSUE TITLE
Reply Count went wild

### ISSUE THREAD

**Issue by hjanuschka** [coralproject/talk#1982]
# frontend
![image](https://user-images.githubusercontent.com/2891702/46737740-96193900-cc9c-11e8-8f80-2b2223b495ab.png)

# my profile tab
![image](https://user-images.githubusercontent.com/2891702/46737705-7f72e200-cc9c-11e8-8fd9-e8ad66d194d5.png)

we are having issues with the reply count, shown in the "my comments" tab in the frontend stream.

it says *5* reply's which is not correct, are there any known issues?
we are not using any count plugin (like the deep one)

internal reference: KRN/MGMT#2058

regards

**Comment by wyattjoh** [comment]
What version of Talk are you running @hjanuschka?

Is this only in a few instances, or widespread?

You can flush the comment counts that are cached in Redis via:

```bash
redis-cli KEYS "cache.sbl*" | xargs redis-cli DEL
```

**Comment by hjanuschka** [comment]
we are using the docker `latest` tag, currently it shows `4.6.5` in the dashboard.

i am not sure if its only a couple of instances, since those are many, and getting loadbalanced anyway, it feels like widespread
are the redis key, supposed to timeout?


the only thing i can imagine is, that we have the full-premoderation enabled, and maybe they count? and also it quiet often happens that comments get removed.

**Comment by wyattjoh** [comment]
How are you "removing" the comments? Rejecting them? The comment counts should update.. But you should definitely try the above set of redis commands, as it'll force expire all of them.

**Comment by hjanuschka** [comment]
😨 27417 removed. but the count is still wrong.

yeah with remove, i mean, "reject" from the admin dashboard. any further ideas?

**Comment by wyattjoh** [comment]
You can check on the `reply_count` parameter on some of the documents that you notice incorrect reply counts. We haven't received reports from other newsrooms relating to this issue, so I'm hoping that it's isolated.

Did flushing the redis keys improve anything?

**Comment by immber** [comment]
@hjanuschka & @wyattjoh I was able to reproduce this behavior in our current latest version of Talk 4.6.5. I'm tagging this as a bug and adding to pivotal. Ticket id # 161659836

The BUG is in incrementing the reply count when Pre-Moderation is enabled. The reply count is being incremented twice, once when the comment is submitted and a 2nd time when the comment is Approved. The reply count is not being incremented by Rejecting a comment in Pre-mod. 

Steps to reproduce:
1. Using talk 4.6.5 with Pre-mod enabled
2. Reply to comment, and check value in MyProfile before moderating and accept/reject, reply_count =1
3. Accept comment in premoderation queue
4. MyProfile reply count will now = 2

**Comment by kgardnr** [comment]
@hjanuschka and @immber this is fixed in v5, gonna close out this issue for now
