### ISSUE TITLE
Change default suspension length

### ISSUE THREAD

**Issue by lriggle-strib** [coralproject/talk#2022]
#### Do you want to request a **feature** or report a **bug**?
Feature

#### Intended outcome:
Have variable or setting that allows the default suspension length to be changed. Currently there doesn't appear to be a way to change this, since it is hard coded here:
https://github.com/coralproject/talk/blob/master/client/coral-admin/src/components/SuspendUserDialog.js#L13

#### Version and environment
4.6.5

**Comment by kgardnr** [comment]
Hey @lriggle-strib, we don't have plans to make suspension time configurable. 

When we built out the suspend user feature, we talked extensively to moderators to decide on some common lengths of time for a "time out" and that's why we chose the options of 1 hour, 3 hours, 24 hours, and 7 days. 

This was also something in which we didn't want to add mental load to the moderators - "how much time do I input if I can give them any amount of time?" - so we opted for a few time periods they can select.

Time outs beyond 7 days seemed to get into "why not ban them then?" territory, hence not making it any longer.

**Comment by lriggle-strib** [comment]
@kgardnr I wasn't saying that I wanted to make it longer than 7 days, I was more saying that I wanted the default radio select to be 24 instead of 3. The available options can stay the same, the one that's selected by default would be what changes.

**Comment by kgardnr** [comment]
@lriggle-strib sorry for misunderstanding Lisa! This is something that we would definitely be interested to add to core if you want to contribute it, but I don't see this coming up on our roadmap as high priority.

**Comment by lriggle-strib** [comment]
Thanks @kgardnr! I'll make sure everyone over here is aware that if they want that feature before it comes up for you guys, we'll have to submit a PR for it.

**Comment by kgardnr** [comment]
Hey @lriggle-strib, closing this one out!
