### ISSUE TITLE
Support ActivityPub federation in Talk

### ISSUE THREAD

**Issue by gelav** [coralproject/talk#2078]
**Do you want to request a feature or report a bug?**

a feature

**Intended outcome:**

Implementation of [ActivityPub](https://activitypub.rocks/). ActivityPub is an open, decentralized social networking protocol. As a result of implementation I want to be able to reply and boost comments in Mastodon.

**Comment by kgardnr** [comment]
@gobengo has mentioned this too! We would love to look at this in more detail. Perhaps the two of you could give us some ideas of how we might do that?

**Comment by gobengo** [comment]
With respect to commenting use cases, my fascination here started when I was first PMing at Livefyre in like... 2011. We had all these bloggers using the free version of the product on their blogs, and those same bloggers were very active commenters on their friends' and peers' blogs. And they thought a lot about comenting on others' blogs as a way to drive new visitors to their own.

So if I'm reading an awesome blog post or article that someone took a lot of time to work on, and it motivates me to also invest some time and energy in leaving a thoughtful (maybe long) response, why should I post that into the comment system below the article (where it could be censored/moderated, deleted, buried after a 'load more' button, ad tracking by the publisher I have no way of knowing about,  I maybe have to agree to T&Cs, give up authorship rights, etc), instead of posting it on my own blog?

If my blog were ActivityPub-enabled, then I could explicitly post a blog post 'in reply to' another blog post (or coral project comment). My server would then do some invisible ActivityPub-handshaking with the parent post's host server (e.g. coral talk), and notify it that my reply exists at another, external URL.

After this, it's kind of up to each community how they want to moderate and display these external comments. They could treat them just like 'local' on-site comments, perhaps after showing up in a moderation queue. Or they could block them entirely.

You can see a prototype of this sort of thing with:
* this parent post on distbin.com: https://distbin.com/activities/a95545eb-3b61-46e4-bb5d-db9efe9d906a
* this reply on a completely separate installation (installation.distbin.com): https://testing.distbin.com/activities/a0c4ddcd-66dc-4a37-8f7e-097cb873ea11
* Try creating new replies by hitting the 'reply' link below any of those, or replying to any ol' URL (e.g. testing your future Coral Talk integration) by creating a new reply from. https://distbin.com/

Also, practically, [distbin is open source](https://github.com/gobengo/distbin/blob/master/src/activitypub.ts) and compatible with the JS/node.js ecosystem that Coral Talk also is implemented in. So there may be room for piggy-backing on the same modules, tests, etc that I implemented over there.

**Comment by gobengo** [comment]
See also this from last time someone at @coralproject asked me about this:
https://twitter.com/bengo/status/962491097548177409

**Comment by gobengo** [comment]
Think about budgeting for it in 2019 planning. I'm available for hire to implement. Or happy to spend an hour or two advising pro bono. I want Talk to be as awesome as possible and become a top app on [permanent.cloud](https://permanent.cloud/apps/7d5aa22a-1f23-4b65-bf6e-e28215d22db9).

I posted a comment on [this blog post on Mozilla Hacks about ActivityPub](https://hacks.mozilla.org/2018/11/decentralizing-social-interactions-with-activitypub/#comment-24194) to this issue so others can weigh in. Maybe we'll get some volunteers!

**Comment by kevinmarks** [comment]
This seems a lot closer to Webmention than ActivityPub

**Comment by gobengo** [comment]
I don't see the evidence to substantiate that it's any closer to Webmention than ActivityPub.

Webmention is like a less expressive, less used, non-JSON-based alternative to ActivityPub Delivery, with no extension process (and no extensibility-via-linked-data, which doesn't require a central registry and process around it). Other projects [have chosen not to implement it at all](https://github.com/tootsuite/mastodon/issues/6074#comment-378452136) (though I wish they would have. The more interop the better).

The W3C Social WG was chartered to build a federation protocol making use of a **JSON-based** social data syntax. Webmention doesn't use JSON. IMO it was was clearly out of scope of the WG charter, but no one belabored that point. It was useful to standardize in addition to ActivityPub mostly for political reasons.

But sure, Talk could still be compatible with federated replies that speak Webmention but not ActivityPub. In practice, when a piece of software gets the step of 'I need to notify resource X', it could first try to use ActivityPub. If resource X didn't accept that, the implementation could then fall back to Webmention. The core required to implement ActivityPub could be 'triggered' by Webmention too.
