### ISSUE TITLE
Cannot see the commenting text box

### ISSUE THREAD

**Issue by hminaeeBrunswicknews** [coralproject/talk#2100]
Hello support,

I installed talk in a cloud. (NB: I am using SSO custom code(tokenUserNotFound) for talk as well)
I am able to see that talk admin page is up and running.
When I connect it to my web app here is what I see:

![image](https://user-images.githubusercontent.com/24658315/49158008-8fe82600-f2f7-11e8-82a5-1a324cf304a1.png)

As you see there is no text box for allowing users to put comment.

Any idea?
Am I missing anything?

**Comment by kgardnr** [comment]
Hey @hminaeeBrunswicknews there is something wrong with your auth plugin, because the signin is not showing (users have to be signed in to leave a comment by default).

Some steps you can try:

1. Have you followed the instructions and thoroughly read the docs here? https://docs.coralproject.net/talk/integrating/authentication/ 

2. Have you ensured your plugin is enabled in your plugins.json?

3. If you're using Docker, are you using the *-onbuild method, to allow for custom plugins?

4. Have you checked your logs and console for potential errors?

5. Do you have someone else you work with who could give you a second pair of eyes? Usually it's a small mistake, and that will resolve it.

Good luck and keep us posted!

**Comment by hminaeeBrunswicknews** [comment]
Thanks @kgardnr  for answering,

I checked everything.
Here is my plugin.json:

{
  "server": [
    "talk-plugin-auth-brunswick-news" 
  ],
  "client": [
  ]
}

However as soon as I update it to :

{
  "server": [
    "talk-plugin-auth-brunswick-news" 
  ],
  "client": [
    "talk-plugin-author-menu",
    "talk-plugin-featured-comments",
    "talk-plugin-flag-details",
    "talk-plugin-ignore-user",
    "talk-plugin-member-since",
    "talk-plugin-moderation-actions",
    "talk-plugin-permalink",
    "talk-plugin-profile-data"
  ]
}

I get the following:

![image](https://user-images.githubusercontent.com/24658315/49169019-3b50a500-f30f-11e8-83e5-80379b79dd09.png)


We had a  working version. The only difference between the not working one and the working version is I use AWS Redis and MongoAtlas instead.
When I open the admin page I see this. I am not sure if this is normal

![image](https://user-images.githubusercontent.com/24658315/49169703-c7170100-f310-11e8-9993-9bbbe400c26d.png)


But I am able to login to admin page of talk.
