### ISSUE TITLE
User role isn't updated/inconsistent on comments

### ISSUE THREAD

**Issue by oafx** [coralproject/talk#2149]
Hi, 

#### Do you want to request a **feature** or report a **bug**?

Bug, probably?
#### Intended outcome:

When changing the user role to staff i expect every comment that was posted by the user to show the staff badge.

#### Actual outcome:

The user badge is only displayed for comments created after changing the role, old comments, created prior to the role change, aren't updated.. this could result in having multiple comments of one user with inconsistent badges on an asset.

#### How to reproduce the issue:

1. Run Talk
2. Create a user
3. Post a comment with that user
4. Change userrole to staff
5. Notice that the badge isn't updated on previous comment
6. Post a new comment with the user
7. Notice you have one comment with and one without staff badge

#### Version and environment

v4.6.11, local dev env and prod docker env.

Kind regards
Chris

**Comment by kgardnr** [comment]
Hey Chris (@oafx), this is actually by design! If someone makes comments when they are not a staff member, and then become a staff member, we want to ensure that's clear. Because news orgs often have staff come and go, and still be active community members, we feel like this is an especially important delineation.
