### ISSUE TITLE
auto login/register with custom user

### ISSUE THREAD

**Issue by StevenYuysy** [coralproject/talk#2167]
#### Do you want to request a **feature** or report a **bug**?

neither

#### Intended outcome:

user auto register (if not register) and login when user login in our site.

#### Actual outcome:

user need to click button with oAuth popup window to sign in.

#### Version and environment

4.7.0

I thought I can write a plugin which expose a router for my site application to get talk's auth token by oAuth token, so I can set this token to localStorage at front end to achieve my goal - auto register/login. But I am not sure there is any other way to do auto login/register.

**Comment by immber** [comment]
@StevenYuysy For SSO integrations with an external auth systems, it works the other way around. The external auth provider signs and sends an Auth token to Talk which Talk validates and uses to create and/or login a user. 
If your external auth provider is already capable of auto registration then you'd want to maintain that user experience by creating and logging in the user through your auth system first, and then send their valid token to Talk so that they are created and logged into Talk as well.

**Comment by StevenYuysy** [comment]
> If your external auth provider is already capable of auto registration then you'd want to maintain that user experience by creating and logging in the user through your auth system first, and then send their valid token to Talk so that they are created and logged into Talk as well.

how can I get this valid token, by writing a plugin and exposing a router for auth systems ?

**Comment by immber** [comment]
You'd need to create a service in your existing auth system to generate and send the token to Talk. This process is outlined in our documentation here: https://docs.coralproject.net/talk/integrating/authentication/#custom-token-integration

**Comment by StevenYuysy** [comment]
Great! I tried set auth token to local storage and figure out it is not work on safari, after changing it to talk render function, it works crossing different browsers.
