### ISSUE TITLE
Comment count not updating to reflect rejected comments

### ISSUE THREAD

**Issue by emilyyount** [coralproject/talk#2292]
#### Do you want to request a **feature** or report a **bug**?
Report a bug

#### Intended outcome:
Update comment count after comments are rejected.

#### Actual outcome:
I visited [this page](https://www.texastribune.org/2019/04/30/trumps-new-asylum-rules-seek-fees-immigrants-bans-some-work-visas/) and noticed it shows the comment count as "1" but there aren't any comments in the stream. The juxtaposition of comment count "1" and "There are no comments yet. Why don’t you write one?" makes it feel broken. 

![Screen Shot 2019-04-30 at 2 18 25 PM](https://user-images.githubusercontent.com/2700000/56987878-3f018580-6b54-11e9-92b3-f6874f295233.png)

#### How to reproduce the issue:
In your own test environment, find a story with comments already in the stream. Reject all of those comments. Check to see if the comment count matches the number of comments in the stream.

#### Version and environment
macOS Mojave Version 10.14.4
Chrome Version 73.0.3683.103
talk:4.8.3-onbuild

**Comment by wyattjoh** [comment]
Hi @emilyyount!

I tried to replicate your issue, but was unable to do so. Have you enabled any plugins that would affect the comment count, such as https://docs.coralproject.net/talk/plugin/talk-plugin-deep-reply-count?

We also perform some caching on the comment count data, if data was modified directly, or an error occurred, the count may not be updated. You can adjust the https://docs.coralproject.net/talk/advanced-configuration/#talk-cache-expiry-comment-count variable in order to get a better rollover of expired counts if that helps!

**Comment by emilyyount** [comment]
Thank you. We haven't enabled any plugins that could affect the comment count. I think adjusting the cache expiry would do the trick.
