### ISSUE TITLE
Multiple tenant domains

### ISSUE THREAD

**Issue by Chavao** [coralproject/talk#2321]
Hello,

We are working on branch `next` and we realized the need to have a domain defined by tenant.

We need to have a domain to provide the tool on the internet and another one to restricted access through our corporate network.

The public domain must have admin routes blocked in nginx and the internal domain will may access the same tenant with all resources allowed.

We think about making `domain` exactly as it is the `domains` and allow the access based on an item in the `domain` list.

What do you think about this? Is there any forecast in your roadmap for this feature?

If this suggestion is a good option, we can submit a PR.

**Comment by kgardnr** [comment]
Hi @Chavao! Thank you for writing this up! I will discuss this with the team and we will get back to you.

**Comment by wyattjoh** [comment]
This is a common problem with applications that rely on domain based tenant sharding. I'd suggest using a feature in nginx such as:

```
proxy_set_header Host the-public-host.com
```

Though this configuration is untested as we don't use Nginx ourselves.

We aren't planning on expanding on the `domain` feature though as this isn't a usecase we plan to support going forward, especially because the `admin` routes are simply serving static views with all the API's still existing on the public `/graphql` routes.

**Comment by Chavao** [comment]
OK, thanks! I'll try with nginx.
