### ISSUE TITLE
[Question] Manually delete/reset SSO user account

### ISSUE THREAD

**Issue by bderen** [coralproject/talk#2711]
Hi guys, is there a way to manually delete/reset SSO user account. We've got an account that is active but somehow authentification with SSO doesn't work for him.

**Comment by wyattjoh** [comment]
Because you already generate the tokens for authenticating yourself, try generating a token for the target user and trying to login yourself. That could help with the debugging process.

If you must delete the user, there is an API mutation called `deleteUserAccount` that an admin token can call for a specific User. Besides that, you could also remove them from the database directly if they haven't interacted with Coral yet because of the authentication issues.

**Comment by bderen** [comment]
Ok, but it requires DeleteUserAccountInput with userID which I know and clientMutationId which I don't know. How can I make it work then?

**Comment by wyattjoh** [comment]
You can just pass `clientMutationId: ""` in the query, it's used by Relay (which we use on the front end).

**Comment by bderen** [comment]
I've successfully deleted the user account. But unfortunately, when I logged in via SSO again, the new user is not being created in coral. Any suggestions?

**Comment by bderen** [comment]
When I retried the operation it did work! Thanks a lot!

**Comment by jacotec** [comment]
@bderen @wyattjoh 
I have exactly the same problem, but after trying around more than 1 hour, I still have **no** clue how I can pass this command to Coral :-(

I've created an access token in the coral-cli, that's well documented ... and then?

I have no idea how the curl command nor the input for the graphiql-UI should look like to delete my user ...

Can anyone please help?
