### ISSUE TITLE
Upgrade Coral 5.3.0 -> 5.4.0 went wrong

### ISSUE THREAD

**Issue by bderen** [coralproject/talk#2758]
After upgrade Coral 5.3.0 -> 5.4.0 got an error:

`{"name":"coral","clusterNode":"master","hostname":"talk-1","pid":1936,"level":50,"err":{"message":"InProgressMigrationDetectedError: migration \"1574287034612\" was in progress","name":"InProgressMigrationDetectedError","stack":"Manager.pending (src/core/server/services/migrate/manager.ts:122:17)\nprocessTicksAndRejections (internal/process/task_queues.js:93:5)\nManager.executePendingMigrations (src/core/server/services/migrate/manager.ts:167:21)\nServer.process (src/core/server/index.ts:219:7)\nbootstrap (src/index.ts:91:7)\n","context":{"_id":"5dfb818119cace90ea302926","id":1574287034612,"clientID":"[Sensitive]","createdAt":"2019-12-19T13:56:17.839Z","state":"STARTED"}},"msg":"can not bootstrap server","time":"2019-12-19T14:15:29.891Z","src":{"file":"/var/www/app/src/index.ts","line":104,"func":"error"},"v":0}`

**Versions:**
- NodeJS: 12.14.0

Did I miss something?

**Comment by wyattjoh** [comment]
When a migration starts, the node completing it must complete it before other nodes of the server can start, it essentially holds a lock.

If no nodes of Coral are running, you can delete the offending record in MongoDB relating to the migration that is stuck in progress, and restart a single node of Coral, which should upgrade the application, and then start it. After that point, all other nodes can boot.

Due to the nature of some migrations causing mutations, we wanted to ensure that the application does not write additional data during a migration to avoid losing integrity. This process will be improved going forward.

Note as well that we have not actually released 5.4.0 yet because we haven't validated some issues we've detected earlier. I wouldn't suggest rolling out releases until we have officially released the version on https://github.com/coralproject/talk/releases.

**Comment by bderen** [comment]
Thanks, indeed the migration was running for a bit longer 1hr, actually only one of them which is reindexing the whole mongo database. Now everything works fine.
