### ISSUE TITLE
Finnish translation

### ISSUE THREAD

**Issue by ghost** [coralproject/talk#2808]
Our company is planning to use Coral in our website and we'd like to contribute Finnish translation to the project.

**Comment by kgardnr** [comment]
Hey @jpkilpi, we would love this contribution, thank you. 

You can check out this PR to see what files you'll need to update, and if you run into trouble or have questions, just let us know. https://github.com/coralproject/talk/pull/2786

What is your site or organization? We've worked with a few sites in Finland.

**Comment by ghost** [comment]
Hi @kgardnr ,  PR added. 

Company is called Mediatalo Keskisuomalainen. It publishes several newspapers in Finland. We are updating our websites and Coral is planned to be the discussion platform for the new sites. Unfortunately I don't have public ETA to give for those sites, but I can let you know when the first one is public.

**Comment by kgardnr** [comment]
That's great @jpkilpi, thank you!

And also if you'd prefer us host and maintain the software for you instead of doing it yourselves, we offer a hosted version of Coral and have a lot of European clients using it. You can always send us an email at support@coralproject.net to discuss more, if you're interested!

**Comment by ghost** [comment]
We'll keep that option in mind. Thank you for the suggestion.

**Comment by kgardnr** [comment]
Fixed in #2811
