### ISSUE TITLE
Securing additional graphql queries

### ISSUE THREAD

**Issue by zekenie** [coralproject/talk#2948]
Hello!

I'm using Coral on a private platform. We want to make sure an attacker cannot see comments on a story unless they have an account (we're using SSO). If I wanted to secure additional graphql quries like `story` and `stories` would it be as simple as modifying the `schema.gql` file [here](https://github.com/coralproject/talk/blob/master/src/core/server/graph/schema/schema.graphql#L3093). From poking around the source it seems like auth is defined declaratively in graphql.

If that's the case, I'll likely fork Coral for our deployments.

Lastly, we're really grateful that coral exists. Thank you.

**Comment by wyattjoh** [comment]
Unforunatly, we currently don't support private conversations.

That being said, because you're using SSO, you can always use a proxy in front of Coral that rejects requests that are not authenticated. See the following example using Caddy:

Using the [`http.jwt`](https://caddyserver.com/v1/docs/http.jwt) plugin, you set the environment variable for `JWT_SECRET={{ SSO Signing Secret }}`:

```
mycomments.example.com {
  jwt /
}
```

You can use any proxy in between, as the gist is that you can secure the requests and require all of them to have a SSO key. If you have further questions, let us know!

**Comment by zekenie** [comment]
Thanks for writing back!

I know we're using Coral a little bit differently than its intended. Out of curiosity, If I were to fork Coral and make a change to the schema.gql file, would that approach work? Or would I need to make more substantial changes

**Comment by wyattjoh** [comment]
I'd expect there to be some issues around auth initialization flows. You'd also have to maintain that fork moving forward.

In short, yes, modifying the schema file might work, but we can't guarantee that changes won't break that support.

**Comment by zekenie** [comment]
Perfect. I'll take that under consideration. Trying to balance maintaining a fork vs maintaining more infrastructure. I'll probably give it a try. Thanks again!
