### ISSUE TITLE
Failed start up following instructions in docs

### ISSUE THREAD

**Issue by mattlinares** [coralproject/talk#2964]
I'm still having the problem as reported in https://github.com/coralproject/talk/issues/2874 and supposedly fixed in https://github.com/coralproject/talk/pull/2917.

Essentially, following the instructions here: https://docs.coralproject.net/talk

for a production deploy results in the browser error:

```Secure Connection Failed
An error occurred during a connection to 178.62.46.128:3000. SSL received a record that exceeded the maximum permissible length.
Error code: SSL_ERROR_RX_RECORD_TOO_LONG
```

Setting `DISABLE_FORCE_SSL=true` in the `docker-compose.yml` environment settings gives access the site by `http` but not at all on the site where I'm embedding comments which requires `https`.

**Comment by wyattjoh** [comment]
Without setting `FORCE_SSL=true`, Coral does not consider the forwarded protocol at all during requests. Any production deployments of Coral should be behind a SSL terminating proxy in order to ensure secure connections.

The error you reported from the browser seems to reference a port `3000`, which looks like a port that Coral uses. Coral does not terminate SSL connections, and does requires a service like Caddy/Nginx in front of it to handle all the SSL.
