### ISSUE TITLE
Allow copying and pasting paragraph formatting; consider adding RTE option for tables

### ISSUE THREAD

**Issue by vosperdw** [coralproject/talk#2966]
I post to the WaPo comments section a lot.  I find it more convienent to compose my comments offline and then cut/paste them into WaPo comments section.

**Expected behavior:**
User pastes comment into comment box.

**Actual behavior:**
Paragraph punctuation is screened out, turning multiple paragraphs int to one and turning rows and columns of date into a single paragraph.

**Related Issues:** 
No.

**Versions:**
Unknown - I am a WaPo commenter, not a sysop.
 
- NodeJS:
Unknown
- NPM:
unknown
- MongoDB:
unknown
- Redis:
unknown
- Browser:
Google chrome
- OS:
Win 10

**Comment by kgardnr** [comment]
Hi @vosperdw! Thank you for writing in and bringing this up. Unfortunately we don't support copy and pasting formatting because of a couple different reasons; one, the formatting could come from multiple sources and it's difficult to predict and handle different types of formatted input; second, we restrict a lot of formatting (currently we limit to bold, italic, and blockquote) to make sure the comment text is easy to read - it's always a give and take of some amount of uniformity and some amount of flexibility. We will be adding some new formatting options in the coming months.

So the best way to do this is to copy and paste your text and then format it yourself before submitting, like adding spaces for paragraph breaks. 

Regarding columns/rows, we don't have plans to support table data - can you give some more examples of when table data would be helpful in the context of a comment, and I can bring this back to our team?

**Comment by vosperdw** [comment]
[CFR covid-19.txt](https://github.com/coralproject/talk/files/4660033/CFR.covid-19.txt)

**Comment by kgardnr** [comment]
We're not going to be adding table support to the RTE in the forseeable future; closing this ticket
