### ISSUE TITLE
Custom JS

### ISSUE THREAD

**Issue by ideallical** [coralproject/talk#3205]
## Search Terms
custom, js, javascript, createStreamEmbed, embed, manipulate, DOM, stream, iframe, communication, bodyClassName, customCSSURL, customJSURL

## Suggestion
I'd like to be able to manipulate the DOM of the embedded stream in the iframe. My proposed solution would be by providing a possibility to load custom JS . e.g by providing `customJSURL` or better, by providing a javascript location via the dashboard, so it's more secure.

## Use Cases
For any DOM modifications you want to do in the stream widget.

e.g. making an expert label on a comment clickable and showing a custom tooltip on which users are prompted to sign up as expert as well.

e.g: changing the `bodyclassName` onclick without re-rendering the whole stream (e.g. website turns to dark-mode)

To my knowledge it's currently not possible to manipulate the DOM of the iframe content when choosing a SAAS solution. 

In coral talk v4 you're able to create a communication channel between the website code and coral talk's code by sending messages over pym.js. I'd really like to customise the stream like this.

**Comment by wyattjoh** [comment]
While this is certainly an interesting proposal, unfortunately I don't think we can implement this.

One of the primary goals of Coral v5+ was to provide stability though features like Typescript and more comprehensive testing. We provide limited customization through [custom css classes](https://github.com/coralproject/talk/blob/master/CSS_VARIABLES.md) that we maintain. We can't however ever guarantee that custom javascript executed in the context of the iframe would remain stable over version releases because by definition, there is no well defined interaction surface or API.

If you find specific features you'd be interested in, be sure to let us know and we'll look into adding it to the platform! At this time however I don't think we have the resources to support custom javascript.
