### ISSUE TITLE
Fetch story by ID if the storyID is defined and update the storyURL

### ISSUE THREAD

**Issue by diegoos** [coralproject/talk#3305]
## Search Terms

update story URL when it changing

## Suggestion

Fetch the story by ID if the `storyID` is defined and update the `storyURL`.

## Use Cases

Sometimes an editor needs to change the URL because the generated slug no makes editorial sense. 
When the slug is edited, the URL changes, but before the edit, the post and story on talk are created and it causes a `DUPLICATED_STORY_ID` error.

I may be wrong, but it looks like the fetch the story by URL even the `storyID` is defined. It would be great if could get the story by ID.

Ok, this creates another problem, the scrape can't find the story metadata anymore if the URL is different.
So the idea is to get the story by ID and if the URL is changed, update it on the story collection.

To avoid this problem I try two ways:

- **1st:** Use the short link (that's not changing) as storyURL.
    But the scrape doesn't work.

- **2nd**: Make a POST request on the talk API whenever is a post is edited.
    It's work, but it increases the complexity in our legacy (😢 ) backend.

**Comment by wyattjoh** [comment]
Thanks for the feedback @diegoos!

We understand that it may be complex to manage URL and ID's of stories that have changing URL's. This is why we provide specific API's for updating URL's on stories as you've used already in your **2nd** option.

We do accept the `storyID`, but that ID is exclusively used to lookup a story with the API, and not used for de-duplicating entries. Anyone using the "lazy story creation" where stories are automatically created in response to loading an embed on them, we have some restrictions in place to prevent abuse. One of these restrictions is not supporting automatic updates for story URL based on having the same ID. Technically, it's possible for a nefarious user to create a page where the embed could render, and they could move discussions off to other pages if we supported updates via the embed. To mitigate this, we prevent these types of updates.

We also don't support redirects for scraping because the URL used should be the absolute and canonical URL for the page where the stream is rendered. The URL embedding the embed needs to match the URL of the story, hence why a redirect on a short URL would not work, because you in fact already redirect the user away from that page.

We're certainly open to suggestions to improve this process, but as it stands we cannot support updating the url if the same id is passed automatically due to the risk of abuse.

**Comment by diegoos** [comment]
Hi @wyattjoh, thanks for your response!

You are right, automatic update can compromise the application.
