### ISSUE TITLE
Use API to get and update story URL

### ISSUE THREAD

**Issue by urlsangel** [coralproject/talk#3848]
## Search Terms

Login, CLI, Update, Story, URL

## Suggestion

We've come across the same issue as described in this post:

https://lefthandbrain.com/change-post-url-keep-comments/

The fix outlined in this post works, but trying to automate this process is non-trivial, as the CLI expects an interactive email/password login to initiate a session.

This has led to experimenting with using [Pexpect](https://pexpect.readthedocs.io/en/stable/index.html), but this seems like a very low-level process to use when running a Django/Python application.

Ideally a token-based API call using a get/update method would be preferred.

#### What do you want to use this for?
Get and update `Story` URLs via an automated server-side process.

#### What shortcomings exist with current approaches?
The CLI requires an interactive email/password login to initiate a session.

**Comment by mattlinares** [comment]
This is an issue we'd like to hear best practice on if possible. Our Coral comments break when a URL changes and we want to implement the most robust, recommended solution. Thanks!

**Comment by tessalt** [comment]
Hi there, if your URLs are not static, we would suggest passing a static `storyID` through the embed code

**Comment by W4yneWu** [comment]
> Hi there, if your URLs are not static, we would suggest passing a static `storyID` through the embed code

Hi tessalt,
Sorry the link to the problem is no longer valid, but I guess we are confronting a similar problem: when the URL has been updated, the Coral component won't be able to load. 
In our case, the storyID is static, so do you suggest that passing the storyID without the storyURL in Coral.createStreamEmbed would do the trick? I mean after the URL being updated, the component can be loaded and previous comments will still be here?
Thanks.

**Comment by nick-funk** [comment]
Hi there folks! I'm Nick, an engineer on the Coral team. I would suggest you use the following two operations.

1. Get an auth token using the local auth API instead of the interactive UI:

`POST` to `https://<YOUR_CORAL_URL>/api/auth/local`

Body:
```
{
  "email": "someadmin@yourdomain.com",
  "password": "someadmin'spassword"
}
```

this will return a payload similar to:

```
{
  "token": "really long auth token with lots of JWT encoded characters"
}
```

You can now use this token to authenticate the next request (i.e. set the `Authorization` header value to `Bearer <YOUR_TOKEN_YOU_JUST_GOT_FROM_LOGIN_REQUEST>`)

2. Then calling `updateStory` via the GraphQL API using the authorization you just got from logging in via the API

`POST` to `https://<YOUR_CORAL_URL>/api/graphql`

Headers:

- `Authorization`: `Bearer <YOUR_AUTH_TOKEN>`

Body:
```
mutation UpdateStoryURLMutation {
  updateStory(input: { 
    id: "<YOUR_STORY_ID>",
    story: {
      url: "<NEW_URL_YOU_WANT_THIS_STORY_ASSOCIATED_TO"
    }
    clientMutationId: "0"
  }) {
    story {
      id
      url
    }
  }
}
```

this will return a payload similar to:

```
{
  "data": {
    "updateStory": {
      "story": {
        "id": "<SAME_ID_AS_BEFORE>",
        "url": "<NEW_URL_YOU_SET_STORY_TO>"
      }
    }
  }
}
```

That should allow you to update the story's URL directly via the API without having to do any Pexpect automation at all.

**Comment by W4yneWu** [comment]
> Hi there folks! I'm Nick, an engineer on the Coral team. I would suggest you use the following two operations.
> 
> 1. Get an auth token using the local auth API instead of the interactive UI:
> 
> `POST` to `https://<YOUR_CORAL_URL>/api/auth/local`
> 
> Body:
> 
> ```
> {
>   "email": "someadmin@yourdomain.com",
>   "password": "someadmin'spassword"
> }
> ```
> 
> this will return a payload similar to:
> 
> ```
> {
>   "token": "really long auth token with lots of JWT encoded characters"
> }
> ```
> 
> You can now use this token to authenticate the next request (i.e. set the `Authorization` header value to `Bearer <YOUR_TOKEN_YOU_JUST_GOT_FROM_LOGIN_REQUEST>`)
> 
> 2. Then calling `updateStory` via the GraphQL API using the authorization you just got from logging in via the API
> 
> `POST` to `https://<YOUR_CORAL_URL>/api/graphql`
> 
> Headers:
> 
> * `Authorization`: `Bearer <YOUR_AUTH_TOKEN>`
> 
> Body:
> 
> ```
> mutation UpdateStoryURLMutation {
>   updateStory(input: { 
>     id: "<YOUR_STORY_ID>",
>     story: {
>       url: "<NEW_URL_YOU_WANT_THIS_STORY_ASSOCIATED_TO"
>     }
>     clientMutationId: "0"
>   }) {
>     story {
>       id
>       url
>     }
>   }
> }
> ```
> 
> this will return a payload similar to:
> 
> ```
> {
>   "data": {
>     "updateStory": {
>       "story": {
>         "id": "<SAME_ID_AS_BEFORE>",
>         "url": "<NEW_URL_YOU_SET_STORY_TO>"
>       }
>     }
>   }
> }
> ```
> 
> That should allow you to update the story's URL directly via the API without having to do any Pexpect automation at all.

Hi Nick,

Thanks for the explanation of the mutation API, which seems to be promising. The only problem is that we don't have a good chance to call the API immediately when the URL changes. So is it possible to create the component without concerning the URL?

Cheers,
Wayne

**Comment by W4yneWu** [comment]
And just one more thing to mention. When the URL is updated, the old URL will still be valid, and it will redirects to the new URL, but Coral won't be working in the new URL.
