### ISSUE TITLE
Delete Users without deleting their comments

### ISSUE THREAD

**Issue by flecki89** [coralproject/talk#3912]
Hi.

For deleting users, I'm using this API-endpoint: https://docs.coralproject.net/api/mutations/delete-user-account
However, this endpoint also deletes their comments.

Is there a way to delete users but keeping their comments?

**Comment by losowsky** [comment]
hi Flecki, not currently - this is designed around GDPR privacy requirements, and since comments can include identifying information, we're deleting the comments as well. 

Otherwise, the way to handle this if you're using SSO would be to have some middleware that renames that commenter as [DELETED] and reassigns their email to a unique generated junk email address.
