### ISSUE TITLE
Facebook login does not work in V7 (Invalid Request Error)

### ISSUE THREAD

**Issue by jacotec** [coralproject/talk#3927]
**Expected behavior:**

Facebook login configured as documented should work for registration and login

**Actual behavior:**

FB registration callback always result in an internal server error from talk:

<img width="659" alt="2022-04-26_23-28-44" src="https://user-images.githubusercontent.com/3321655/165396182-a6704f1d-910d-4a12-82a6-a303e68cafe4.png">

**Related Issues:** 

**Versions:**

- NodeJS: 14.18.0
- NPM: 8.0.0
- MongoDB: 4.4
- Redis:
- Browser: Edge, Safari, Chrome, Firefox
- OS: Windows, MacOS

**Comment by tessalt** [comment]
Hi there, thanks for your report, we'll investigate this.

**Comment by jacotec** [comment]
@tessalt Thanks! BTW: Google has the same issue with the callback URL and does not work as well. Wanted to activate this today and ran into the issue.

**Comment by nick-funk** [comment]
Hi @jacotec, I was able to get this working for Google by adding a redirect URI to the OAuth 2.0 Client ID.

- Head over to https://console.cloud.google.com/apis/credentials
- Select your project
- Under `OAuth 2.0 Client IDs`, find the identifier that you are using for your Google OAuth and click on it
- Add a redirect URI under `Authorized redirect URIs` of the format `https:// {YOUR_CORAL_DOMAIN} /api/auth/google/callback`
- Save

Once I did this, I was able to register and sign in with Google.

I believe something similar is going on with Facebook, so I'm digging into that now. I'll update once I've found the appropriate steps for setting valid redirect URI's for OAuth 2.0 on Facebook as well!

**Comment by nick-funk** [comment]
Hi @jacotec, I've looked into the error you've posted for Facebook. It looks like it's very similar to what I had to do for Google.

Can you try the following?

- Head to https://developers.facebook.com/apps
- On the left nav bar, go to `Settings` > `Advanced`
- Select your Facebook app you're using with Coral
- Under `Domain Manager` add `https://{YOUR_CORAL_DOMAIN}`
- Under `Shared Redirect Allow List` also add `https://{YOUR_CORAL_DOMAIN}`
- Save Changes

Try that and see if it allows you to login with Facebook. If not, let us know, and I can try and dig deeper to see if this is an issue on our end instead of redirect permission issues.

**Comment by jacotec** [comment]
HI @nick-funk,

that's how I've configured it, but I'm seeing the same issue with all auth endpoints. Trying to connect to my Keycloak (OpenID-Connect), my redirect URI is also not working, giving the same error message.

In your above example, what do you get when you just call the URL "https://{yourdomain}/api/auth/facebook/callback" in a browser?

I'm getting:

`{"error":{"id":"19f22680-e24a-11ec-8fad-35b49bfc13a9","traceID":"19f1d860-e24a-11ec-8fad-35b49bfc13a9","code":"INTERNAL_ERROR","type":"INVALID_REQUEST_ERROR","message":"Interner Fehler"},"report":null}`

... and the same error for Google and OpenID connect as well.

Am I overseeing something?

**Comment by nick-funk** [comment]
If you try and directly call your `https://{yourdomain}/api/auth/facebook/callback` in browser, it will always fail because it does not have the correct referral and token headers to validate a user. Me doing that with my domain is also never going to work.

If you want to use OpenID Connect, I would suggest you use `Admin > Configure > Authentication > Login with OpenID Connect` for that auth provider. You may already be doing that though.

If you're seeing `INVALID_REQUEST_ERROR` with oauth redirect URL's, it's usually because the OAuth provider (Google, Facebook, etc) don't have your domain listed as an allowed domain for OAuth. We encountered this when setting up various sites, it's almost always a missing redirect or script permission on the side of your OAuth provider. 

The reason I say this isn't to try and ignore what you're going though, it's that we have several clients happily using our FB/Google auth with no problems currently and if this was an issue with our code specifically, I feel like they would also be complaining that their many FB/Google users can't login and comment.

**Comment by Sentynel** [comment]
Yeah, we use Google and Facebook login and they were an absolute pig to set up in the first place so I sympathise, but both definitely work correctly. On the provider side, make sure you've got the correct domains in the relevant domain allow lists (e.g. we have `comments.ourdomain.com` and `devcomments.ourdomain.com`) and the exact callback URLs (`https://comments.ourdomain.com/api/auth/google/callback` etc). On Coral's side, make sure you have the correct values for the app ID and secret in each case (e.g. Facebook uses a numeric app ID, Google uses a .googleusercontent.com domain name for the app ID).
Trace the request flow with the browser console to see if the provider gives a sensible error message anywhere in the process.

**Comment by jacotec** [comment]
Hi,

thanks for all your feedback. I've got it working now by adding the TRUST_PROXY in the Coral config, including the use of Keycloak as SSO.

In fact I'm only using Keycloak now and have realized FB, Google and Twitter login there.
