### ISSUE TITLE
Missing 'rapported' tab in V7

### ISSUE THREAD

**Issue by tgravemaker** [coralproject/talk#4076]
Hi, 

when testing the implementation of V7 I noticed that somehow we are missing the 'rapported' tab. This tab was available in the previous (V4) version we are using. See screenshots ('Gerapporteerd' is 'Rapported')

![Schermafbeelding 2022-10-12 om 15 40 38](https://user-images.githubusercontent.com/105290986/195359330-9f3af5ae-13a4-4f79-83fe-8b86baf41abb.png)

![Schermafbeelding 2022-10-12 om 15 41 15](https://user-images.githubusercontent.com/105290986/195359372-e46d0665-e123-4ee7-ba2f-00ca7236d131.png)

My question is, how does is this tab supposed to work? i would expect to see flagged/reported comments below that tab, along with the comments with forbidden and suspected words, but now we have to sift manually through all the comments below 'approved' to check on rapported comments.

**Comment by ideallical** [comment]
Looking in the code, the `reported` column only shows when the moderation is set to POST or when there is at least one reported comment. 
And reported comment in coral talk means: status = NONE + 1 flag.
So not status = ACCEPTED + 1 flag, what you might expect.


So when you set moderation to POST, then users can flag the posts and you can see them there. As moderation POST means all new comments get status = NONE, meaning unmoderated, but still visible on the website.

However, in our use case, we want both. Let an AI decide wether a comment is APPROVED or DECLINED.
And then still give users the option to flag an accepted comment.

My solution was to add a MongoDB trigger that checks when there is a new CommentAction with actionType=FLAG, and then set the comment's status to NONE if that was the first time it was flagged.

The comment is then shown in the reported column. However, the number of reported comments doesn't get a +1.
Other than that, when I accept or decline the reported comment, the reported tab disappears because it goes from 0 to -1 to -2.

**Is there a way to keep the reported count aligned?**
I see:
reported count in `sites`[0]commentCount[moderationQueues][queues][reported]` however changing this value doesn't seem to change the value in the reported column.

**Comment by tessalt** [comment]
Yes that is correct, the "reported" tab will show reported comments that have not been approved. Comments that have been approved and then are reported will not be in the reported queue.
