### ISSUE TITLE
Missing index on commentActions

### ISSUE THREAD

**Issue by remko79** [coralproject/talk#4092]
**Expected behavior:**
Fast deletion of stories including comments

**Actual behavior:**
Slow due to missing index

When deleting a story, it's very slow due to a missing index on collection `commentActions`. It needs an index on tenantID and storyID

**Comment by tessalt** [comment]
Hi there, we'll look into this

**Comment by remko79** [comment]
Thanks, I think there might be more indexes missing, but currently this one is the main problem for deletion for us

**Comment by ideallical** [comment]
I was looking into this as well, for the "for review" column.
And I only just now realised there is an INDEXES.MD file, that gives some information about indexes.
What is the history or reasoning about this file?

As I'd expect all indexes to be created on setup of the project, but now I guess? I have to add these indexes found in INDEXES.MD manually after installation ?

**Comment by remko79** [comment]
Well, you'd say that's why there are migrations, but I doubt all those new indexes are in the migrations

**Comment by remko79** [comment]
There's another index missing on the same table when deleting a user, it needs an index for tenantID, userID

**Comment by nick-funk** [comment]
The indexes listed in `INDEXES.md` are to be applied manually by the database administrator. We stopped using migrations due to the fact that for many clients optimizing Mongo, they did not require all possible indices listed. Instead, we now list the indices in the markdown file with full explanation as to their purposes so that users of Coral can decide what is best for their clusters.

For many, they read through our reasonings on the indices and choose to combine or multi-purpose several indexes together to optimize memory usage and index retrieval within Mongo. This is tremendously helpful on large scale deployments.

I understand it is frustrating to not have a migration handle all of this for you, but given how different our various SaaS customers are using their Coral and Mongo instances, we opted for a more flexible approach that allows complete deployment control for our SaaS and open source users!
