### ISSUE TITLE
Upgrade to v8.0.3 is not working

### ISSUE THREAD

**Issue by yogeshbeniwal** [coralproject/talk#4227]
**Expected behavior:**
Upgrade to v8.0.3 from v8.0.2 should be without any issue
**Actual behavior:**
Upgrade to v8.0.3 is resulting in 502 bad gateway error. No configuration change was performed while upgrading from v8.0.2.

Error shown in web server logs:

`[error] 1718#1718: *491 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: XXXX, server: XXXX.com, request: "GET /favicon.ico HTTP/2.0", upstream: "http://127.0.0.1:5000/favicon.ico", host: "https://XXXX.com", referrer: "https://XXXX.com/admin"`

Service is running.
`
tcp        0      0 127.0.0.1:5000          0.0.0.0:*               LISTEN      43077/docker-proxy
`

**Related Issues:** 

**Versions:**

- NodeJS: 
- NPM:
- MongoDB: 6
- Redis: 7
- Browser: Chromium based
- OS: Ubuntu 22.04

**Comment by nick-funk** [comment]
Hi @yogeshbeniwal! I believe you may be seeing these issues because you are using an unsupported version of Mongo and and Redis with Coral.

If you check the Coral docs (https://docs.coralproject.net) we only support Mongo 4.2/5 and Redis 3.2.

If your bad gateway response continues, I would suggest looking into your network config in front of Coral. We have successfully deployed Coral 8+ to several of our SaaS customers without any problems thus far which leads me to believe it might be on your end rather than a specific bug in Coral?

**Comment by yogeshbeniwal** [comment]
@nick-funk Redis 3.2 is many years old. Dn't think its even supported by Redis team anymore.

**Comment by yogeshbeniwal** [comment]
Resolved by v8.0.4
