### ISSUE TITLE
Why is it impossible to change Coral moderation settings

### ISSUE THREAD

**Issue by BrooklynGersh** [coralproject/talk#4280]
It seems every single comment on my website (Streetsblog NYC, whose back end is operated by Lede) requires moderation on Coral, yet there does not appear to be any way to change the settings to make them less sensitive. Help.

website: http://nyc.streetsblog.org

Using Coral for comment moderation.

Gersh

**Comment by losowsky** [comment]
Dear Gersh

What labels are on the comments in the mod interface? Have you chosen to set all comments for Premoderation? (Configure>Moderation) or all new accounts to premoderation (Configure>Moderation>New Commenter approval)?

Best

Andrew

**Comment by BrooklynGersh** [comment]
I’ll do my best to answer you, Andrew, and thanks for getting back to me. I am awfully old, but I feel pretty tech-savvy. And am finding Coral to have too few settings to change. But here goes:

> What labels are on the comments in the mod interface?
> 

Almost every comment comes in with “possible banned word” as the tag. When you click “details,” however, all I get is this, which provides no information for me:



And to be clear: there was nothing in this comment (or, indeed, most of them) that are objectionable by our standards at all. Here is the comment that got flagged: "Let’s face it, we’re talking about cars here, not sheds. This is nothing but another move by regressive elderly auto drivers to destroy our city and environment. Let’s focus on the real problem: Manhattan needs to end all free private vehicle storage on our public streets. Separately, if you don’t like city noise, you should not live in a city.”

Or this one:



>  Have you chosen to set all comments for Premoderation?
> 
No. Under “configure —> general —> moderation,” I have not selected premoderation, because that would require a staffer to spend precious hours to read and approve all the comments when, in reality, there might simply be one or two that don’t meet our standards.

I suppose I could "Pre-moderate all comments containing Suspect Words,” except that when I click on the word list, it’s blank. Do you have a list of objectionable words I can cut and paste? My imagination is limited to the basic taunts I learned in middle school in 1979.

There is also this, but I don’t know how to use it:



Thanks. Any help you can give will be greatly appreciated.

—
Gersh Kuntzman (he/him)
Editor
Streetsblog
Cell: (347) 512-4651
Twitter: @gershkuntzman

Why not check out Streetsblog <http://nyc.streetsblog.org/>?

**Comment by losowsky** [comment]
Got it. "Possible banned word" means that the Banned Words search has timed out before returning a result. 

1. Do you have any banned words in the list under Configure>Banned and Suspect Words? You should have at least one or two. If not, try adding one at least. The system expects that a site will restrict at least one word or phrase from the comments.
2. If you do, do you have a very high number (more than 7000)?
3. If neither of these are true, then this is down to how Lede has set up your install, and what they've chosen the timeout period to be. We don't work directly with them at all, as they're using our open source code, so you'll need to ask them to change that timeout variable to a longer length. 

Best wishes

Andrew

**Comment by BrooklynGersh** [comment]
I don’t understand what you mean by timeout period.

—
Gersh Kuntzman (he/him)
Editor
Streetsblog
Cell: (347) 512-4651
Twitter: @gershkuntzman

Why not check out Streetsblog <http://nyc.streetsblog.org/>?

**Comment by losowsky** [comment]
Hi Gersh

This is a code question for how your servers are set up. 

In short, when someone hits "submit" on a comment, that comment then passes through a bunch of filters inside Coral, including "Does it contain a banned word?", "Is this person logged in?", "Is this article set to pre-moderate everything?" and so on. 

If any of these questions gets stuck on the server, we don't leave the comments locked indefinitely until it gets an answer, as that would break it for everyone. Each query "times out" (as in stops trying and returns an error) after a set period, and then a particular action kicks in. In the case of Banned Words, what it does is say "OK this comment might or might not contain a Banned Word, we don't know because we asked the question to the server and it didn't reply fast enough" and it 
sends the comment to one of the queues, either REPORTED (which is still on the page and everyone can still see it, it's not held back, but is flagged for moderator attention) or PENDING (which isn't yet on the page and is held back for moderator review) and tags it with "Possible Banned Word" because Coral doesn't know, it didn't get an answer in time. That length of time is set in the code by the team maintaining that code. That length of time is what I referred to above.

If you don't have any Banned Words at all, then Coral will get confused and say "We can't find the list in time! It should be there!" but it sounds like you do have banned words in your Banned Words and Phrases list, so that isn't relevant. 

Either way, as I said, as long as you do have Banned Words in your Banned Words list, and the number of words isn't huge (7K+), then the problem is in the length of time set by Lede.

Lede is not a customer of ours and we have no formal relationship with them, so we cannot change this ourselves or give them personalized support looking at their setup. 

Does that make sense?

**Comment by BrooklynGersh** [comment]
Now THAT makes sense! Thanks. ---Gersh KuntzmanEditor in chiefStreetsblogw) 347-512-4651I often work remotely so please make sure I have your phone ***@***.*** Jul 7, 2023, at 2:25 PM, losowsky ***@***.***> wrote:﻿
Hi Gersh
This is a code question for how your servers are set up.
In short, when someone hits "submit" on a comment, that comment then passes through a bunch of filters inside Coral, including "Does it contain a banned word?", "Is this person logged in?", "Is this article set to pre-moderate everything?" and so on.
If any of these questions gets stuck on the server, we don't leave the comments locked indefinitely until it gets an answer, as that would break it for everyone. Each query "times out" (as in stops trying and returns an error) after a set period, and then a particular action kicks in. In the case of Banned Words, what it does is say "OK this comment might or might not contain a Banned Word, we don't know because we asked the question to the server and it didn't reply fast enough" and it
sends the comment to one of the queues, either REPORTED (which is still on the page and everyone can still see it, it's not held back, but is flagged for moderator attention) or PENDING (which isn't yet on the page and is held back for moderator review) and tags it with "Possible Banned Word" because Coral doesn't know, it didn't get an answer in time. That length of time is set in the code by the team maintaining that code. That length of time is what I referred to above.
If you don't have any Banned Words at all, then Coral will get confused and say "We can't find the list in time! It should be there!" but it sounds like you do have banned words in your Banned Words and Phrases list, so that isn't relevant.
Either way, as I said, as long as you do have Banned Words in your Banned Words list, and the number of words isn't huge (7K+), then the problem is in the length of time set by Lede.
Lede is not a customer of ours and we have no formal relationship with them, so we cannot change this ourselves or give them personalized support looking at their setup.
Does that make sense?
