### ISSUE TITLE
Errors that seem to have no effect

### ISSUE THREAD

**Issue by kenara** [coralproject/talk#4473]
**Expected behavior:**

No errors

**Actual behavior:**

I have a coral embed on my page and every few seconds get these errors when viewing with developer tools:

```
Firefox can’t establish a connection to the server at wss://coral.mysite.org/api/graphql/live. client.ts:545:18
The connection to wss://coral.mysite.org/api/graphql/live was interrupted while the page was loading.
```
It doesn't affect commenting or the display of comments but makes it look like we don't know what we're doing. 
Maybe we don't...

Is this important?
Can we do something about it?

**Related Issues:** 

**Versions:**

Coral v8.5.3 (docker)

- NodeJS:
- NPM:
- MongoDB:
- Redis:
- Browser:
- OS:

**Comment by nick-funk** [comment]
The inability to establish a connection over `wss://...` is the client saying it can't establish a web socket connection to your Coral pods/instances. The web sockets are used for live updates to make the stream update when a person comments, replies, etc so that new comment items appear live in stream as they happen in real time.

This could be happening for a variety of reasons, all of which will be specific to your hosting infrastructure:

- The reverse proxy/load-balancer in front of your Coral pods is not set up to handle web socket traffic
- The caching layer (CDN) you're using to serve your static assets (STATIC_URI) is not forwarding and handling web socket traffic
    - We have found various CDN's do not support web sockets, which is why we at Coral use specific CDN providers when routing and hosting our assets
- The host site providing your articles and commenting streams is not set up to forward web socket traffic

Unfortunately, all of these variables are external to Coral as they are part of the hosting infrastructure around Coral. This means we can't give you specific step-by-step instructions for how to set this up as it is different for every organization what they choose to host their services on.

You'll have to diagnose and configure your infrastructure as needed to resolve the web socket connection issues yourself.

Hopefully that helps your investigation!
