### ISSUE TITLE
OpenID Connect HTTP Callback Url

### ISSUE THREAD

**Issue by knom** [coralproject/talk#4507]
We have CORAL running on an HTTPS instance of Fargate in AWS.

Expected behavior:
Using Docker installation guide at https://docs.coralproject.net/, Redirect URI in OpenID Conenct login is having http instead of https i.e.

http://talk.sitename.com/api/auth/oidc/callback instead of https://talk.sitename.com/api/auth/google/callback

Actual behavior:
OpenID Connect redirect URI should include https instead of http
The Config URL Textbox shows the hardcoded http://... value - and it cannot be changed.

Related Issues:
Similar to #3667 - but for OpenID Connect.

Versions:
Using latest version of Docker installation

**Comment by losowsky** [comment]
Thanks - well take a look.

**Comment by nick-funk** [comment]
We do not support serverless hosting or network stacks with Coral.
Our system reconstructs secure and insecure url's when it finds tenants and other requests here:
https://github.com/coralproject/talk/blob/develop/server/src/core/server/app/url.ts#L33

The reason you're likely seeing `http` instead of `https` is that somewhere in the network stack in front of your Coral pods (load balancer, reverse proxy), it is stripping the `https` when it redirects the requests to Coral.

**Comment by knom** [comment]
Hey @nick-funk:
I have a question regarding support.

- **Serverless Hosting**: Do you refer to AWS Fargate - or Docker in general being unsupported?
   If Fargate only, what would be a supported AWS Container environment?

- **Networking stacks**: likewise :-)

Thanks for your help :-)
