### ISSUE TITLE
Story cache - DATA_CACHING_NOT_AVAILABLE

### ISSUE THREAD

**Issue by MadsNRK** [coralproject/talk#4547]
Problems caching stories in Coral

**Expected behavior:**
From admin > story details > "Recache story". When pressing this button, I expect the story to be cached or recached.

**Actual behavior:**
Console error: DATA_CACHING_NOT_AVAILABLE

**Versions:**

- NodeJS: v18.19.0
- MongoDB: 7.0.5
- Redis: 7.2.1
- Coral: 8.7.2

**Comment by losowsky** [comment]
Hi there, when your team upgraded from v7 to v8, did they enable the Redis Cache as detailed in our migration docs? https://docs.coralproject.net/migrating-7-to-8

**Comment by MadsNRK** [comment]
Hi

Thanks for your reply.
I will check with my team what specs we are running on in the production enviroment. But is the same hardware specs required to run coral in a develompent enviroment? Does the software check what resources it has avaliable, and disable the cache if the specs are not met?

Thanks

Best regards
Mads

**Comment by losowsky** [comment]
Version 8 is built around optimizing for the redis cache being implemented. We can't guarantee performance if you choose to go in another direction.

**Comment by MadsNRK** [comment]
We are not looking to go in another direction. But for some reason the "Story cache" is not working in our setup, and I'm just trying to figure out why. Therefor I'm wondering if the hardware setup has a direct impact on the error message we encounter (DATA_CACHING_NOT_AVAILABLE) or if there's a setting we have overlooked or something :)

**Comment by losowsky** [comment]
I'm afraid as an open source user, we can't dedicate the resources to help you troubleshoot your own set up. Good luck in figuring it out!

**Comment by ideallical** [comment]
It was not clear for us either from reading just the migration docs.
However, we found it hidden in the main docs. Turns out you need to turn on a feature flag using a mutation:
https://docs.coralproject.net/api/mutations/enable-feature-flag

Which feature flag?
This one: [DATA_CACHE](https://github.com/coralproject/talk/blob/develop/server/src/core/server/graph/schema/schema.graphql#L588-L592)


So **POST** to your graphQL endpoint **/api/graphql**:
Using the header:
**Authorization: Bearer here your admin jwt**
And this json in the body:
```
mutation {
  enableFeatureFlag(
    input: {
      clientMutationId: "turn-on-cache", 
      flag: DATA_CACHE
    }) {
        clientMutationId
        flags
    }
}
```

Once that is done, your tenant (found out by the domain the graphQL endpoint is on), will gain this feature flag.
Not sure if this is needed, but you might want to restart the servers as the tenant configuration is cached.
