### ISSUE TITLE
post comment query going in pending state other then role:"ADMIN" in v9.0.6

### ISSUE THREAD

**Issue by Shubhamsharma585** [coralproject/talk#4628]
**Expected behavior:**
It should post the comment, or there should be any setting to enable or disable post for making comments other users.
**Actual behavior:**
comment is not posting, graphgl query is going in pending state.

**Related Issues:** 
https://github.com/coralproject/talk/issues/4626

**Versions:**
- Coral: 9.0.6
- NodeJS: 18.16
- PNPM: 8.0 
- MongoDB: 4.2
- Redis: 3.2
- Browser: Chrome
- OS: win11

**Comment by Shubhamsharma585** [comment]
@nick-funk

**Comment by losowsky** [comment]
Hi there! 

If comments from non-admins/staff are going into Pending, that is most likely because you have changed a setting to Always Premoderate, either globally via the option at [URL]/admin/configure/moderation, on the article via the Configure menu on the article page, or that user/that user's email domain is set to Always Premoderate, or you have an AI filter running that is sending comments to the Pending queue. Can you check all of those settings?

Also no need to tag individual engineers please, we track issues on our repos as a team. 

Thank you!

**Comment by Shubhamsharma585** [comment]
Thanks for quick reply. I have not changed setting to Premoderate. I am just running fresh copy of coral in local version with node 18.16.0.
Note:- I tried running with docker image that use 18.20.2 is working fine for the same issue.

**Comment by losowsky** [comment]
Hm. Do the comments in pending have any kind of tag on them?

**Comment by losowsky** [comment]
We haven't heard any more information for several months so I'm closing the ticket. If you have any more information to add, feel free to re-open
