### ISSUE TITLE
Separate labels for pre-moderated stories and when user posted a suspect word

### ISSUE THREAD

**Issue by flecki89** [coralproject/talk#4693]
## Search Terms

submittedAndWillBeReviewed, pre-moderate label, suspect word

## Suggestion

Currently, the label `comments-submitStatus-submittedAndWillBeReviewed` is used for these two cases.
- User writes a comment that contained a suspect word
- User writes a comment for a story that is set to "Pre-moderate all comments"

It should be possible to have separate labels for these two cases.

## Use Cases

When a user posts a comment, we want to inform them why it does not appear immediately in the comment stream. 

#### Usage of a suspicious word
"Your comment contains words that are on our stop word list. The comment will therefore be checked by our community team for compliance with the forum rules before it goes online. Details can be found in section x.y.z of our forum rules."

#### Article is set to pre-mod (mainly used for articles about a current controversial topic)
"There were a particularly large number of violations of our forum rules in comments on this article. Therefore, all comments on this article will be checked by our community team before they go online. Details can be found in point x.y.zz of our forum rules."

**Comment by losowsky** [comment]
Hi there, 

I'm going to close this because we deliberately don't do this for a few reasons. 

Firstly, we give the same "Your comment will be reviewed by a moderator" message for all reasons comments are held back (user history, email domain, words, AI screening, articles, etc) so that commenters don't start trying to reverse engineer ways around the safeguards. 

Secondly, if you want to let readers know that the article is set to premod, we recommend that you use the existing "Post a message" feature at the top of the comments, so that commenters can be informed ahead of time, before the write their comments, which we believe is a better experience than having them write what could be a long and detailed time-sensitive comment and only then discover that the article is being premodded.
