### ISSUE TITLE
Is there a way to allow anonymous commenting?

### ISSUE THREAD

**Issue by supermario12342003** [coralproject/talk#4697]
Im trying to self host this great comment tool, but i need a little customization, i need user to be able to comment without signing up, is there a simple way to change the code to get this? Does anyone else need this feature?

**Comment by losowsky** [comment]
We don't have this, by design. A core ability for moderators to evaluate a comment is to be able to see that user's history, and also to have the ability to ban people who are abusive/trolls/spam. If you allow every comment to be posted without sign up, you make any kind of user moderation all but impossible, which goes against the principles on which we were founded. 

If you wanted to connect an SSO that generated random user ids every time, I suppose you could do that. But if someone tried to add "Post without an account" to our code, I can't imagine that we'd be merging in any such ability for the foreseeable future, and we strongly urge you not to launch a community with this feature.
