### ISSUE TITLE
Preventing unverified email members from commenting? 

### ISSUE THREAD

**Issue by atsbob** [coralproject/talk#4698]
## Suggestion

I'm not sure if my configuration is incorrect but I have email-only signups but I've noticed in testing that I can comment and have that comment go live (unmoderated) even if the new account is not verified. Isn't there an option for something like this? I am using version 9.5.3. 

## Use Cases

Assuming this feature does not exist, it would be good in order to prevent abusive spammers from signing up with any bogus email address before commenting.

**Comment by losowsky** [comment]
Focusing on the goal of preventing spammers, we have several anti-spam measures.

- you can integrate with Akismet or a similar spam detection AI service
- you can set certain user registration email domains to always premoderate or autoban
- you can add common spam urls to banned/suspect lists
- you can set all new commenters to have X comments have to be approved before they can post without review

Also fwiw, our experience says that email verification hasn't prevented spam, it just slows it down a little. Most large spam companies have automated clickthroughs for email registration that fakes verification.

If you're wedded only to that solution, we haven't added verification to our own auth system because it is by design extremely barebones. The vast majority of professional orgs using Coral (we estimate more than 95%) use their own SSO, and so the responsibility for registration and verification is outside of Coral's visibility for the core use cases for which Coral was built. If you want this functionality, however, you could utilize External Moderation Phases to POST all comments to a service that checks if the comments by any given user should go straight to PENDING or not, based on their registration status. 

I hope that helps!
