### ISSUE TITLE
Import from Disqus?

### ISSUE THREAD

**Issue by iliakan** [coralproject/talk#4708]
Hello!

We were using Disqus for quite a while, but its ads became so nasty, can't tolerate any more.

Is there an utility to import comments into Coral?

P.S. I found https://github.com/coralproject/talk-importer and https://github.com/coralproject/talk-importer-disqus, should I use any of them?

**Comment by losowsky** [comment]
HI there

Those two importers definitely don't work, as they're for a deprecated version of Coral. Our most recent importer is here: https://github.com/coralproject/coral-importer it's not Disqus specific but it will import data that has been exported into a specific csv format. That said, we haven't used it in a while so we can't guarantee if it'll work with the latest version.

In addition, you should be aware that if your current community uses Disqus to sign in instead of an SSO, you won't get the account information required from Disqus to migrate the user accounts. It's much easier and safer to start again with your community, especially in that situation.
